spring.datasource.url=jdbc:postgresql://localhost:5432/fpc_football_booking
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

jwt.secret=Zryqk6EDC3TEdEPU37Msh53Mty+DJ/Tnx2n1u94NzOM=
jwt.expiration=3600000